name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/backend.yml'
      - 'infrastructure/**'
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/**'
      - 'backend/**'
  workflow_dispatch: null

permissions:
  id-token: write
  contents: read

jobs:
  backend-quality-gates:
    name: Backend Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.9.5

      - name: Format check
        run: ./backend/do fmt-check

      - name: Linting
        run: ./backend/do lint-check

      - name: Test
        run: ./backend/do test

  deploy-dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    needs: [backend-quality-gates]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::465836752303:role/lexloop-cicd-deploy-role
          aws-region: eu-central-1

      - name: Build lambda bundle
        run: cd backend && ./do build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Check infra format
        run: ./infrastructure/do fmt-check

      - name: Lint infra
        run: ./infrastructure/do lint

      - name: Deploy dev environment
        run: cd infrastructure && ./do apply-auto dev
        env:
          TF_VAR_supabase_access_token: ${{ secrets.SUPABASE_DEV_ACCESS_TOKEN }}
